/**:
  ros__parameters:
    mask_topic: /event_mask
    contours_topic: /object_contours
    edges_topic: /object_edges
    publish_edges: true
    use_dilate: true
    kernel: 5
    kernel_shape: ellipse
    dilate_iters: 2 # augmente la taille des countours pour fermer les trous
    connectivity: 10
    min_area: 20
    enable_temporal_noise_filter: true
    temporal_small_area_max: 80
    temporal_min_persist_frames: 2
    temporal_match_distance: 8.0
    temporal_track_ttl_frames: 2
    contour_thickness: 1
    chain_approx: true
